const router = [
  {
    id: '1',
    name: 'Users',
    icon: 'user',
    route: '/users',
    roles: ['admin', 'user'],
  },
  {
    id: '11',
    menuParentId: '-1',
    breadcrumbParentId: '1',
    name: 'Create User',
    route: '/users/create',
    roles: ['admin', 'user'],
  },
  {
    id: '12',
    menuParentId: '-1',
    breadcrumbParentId: '1',
    name: 'Edit User',
    route: '/users/edit/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '13',
    menuParentId: '-1',
    breadcrumbParentId: '1',
    name: 'View User',
    route: '/users/view/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '2',
    name: 'Feeds',
    icon: 'star',
    roles: ['admin', 'user'],
  },
  // {
  //   id: '21',
  //   menuParentId: '2',
  //   breadcrumbParentId: '2',
  //   name: 'Players',
  //   icon: 'star',
  //   route: '/players',
  //   roles: ['admin', 'user'],
  // },
  // {
  //   id: '211',
  //   menuParentId: '-1',
  //   breadcrumbParentId: '21',
  //   name: 'View Player',
  //   route: '/players/view/:id',
  //   roles: ['admin', 'user'],
  // },
  // {
  //   id: '212',
  //   menuParentId: '-1',
  //   breadcrumbParentId: '21',
  //   name: 'Edit Player',
  //   route: '/players/edit/:id',
  //   roles: ['admin', 'user'],
  // },
  {
    id: '22',
    menuParentId: '2',
    breadcrumbParentId: '2',
    name: 'Teams',
    icon: 'flag',
    route: '/teams',
    roles: ['admin', 'user'],
  },
  {
    id: '221',
    menuParentId: '-1',
    breadcrumbParentId: '22',
    name: 'View Team',
    route: '/teams/view/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '222',
    menuParentId: '-1',
    breadcrumbParentId: '22',
    name: 'Edit Team',
    route: '/teams/edit/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '223',
    menuParentId: '-1',
    breadcrumbParentId: '22',
    name: 'Create Team',
    route: '/teams/create',
    roles: ['admin', 'user'],
  },
  {
    id: '23',
    menuParentId: '2',
    breadcrumbParentId: '2',
    name: 'Leagues',
    icon: 'database',
    route: '/leagues',
    roles: ['admin', 'user'],
  },
  {
    id: '231',
    menuParentId: '-1',
    breadcrumbParentId: '23',
    name: 'View League',
    route: '/leagues/view/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '232',
    menuParentId: '-1',
    breadcrumbParentId: '23',
    name: 'Edit League',
    route: '/leagues/edit/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '233',
    menuParentId: '-1',
    breadcrumbParentId: '23',
    name: 'Create League',
    route: '/leagues/create',
    roles: ['admin', 'user'],
  },
  // {
  //   id: '24',
  //   menuParentId: '2',
  //   breadcrumbParentId: '2',
  //   name: 'Schedule',
  //   icon: 'schedule',
  //   route: '/schedule',
  //   roles: ['admin', 'user'],
  // },
  // {
  //   id: '241',
  //   menuParentId: '-1',
  //   breadcrumbParentId: '24',
  //   name: 'View Schedule',
  //   route: '/schedule/view/:id',
  //   roles: ['admin', 'user'],
  // },
  // {
  //   id: '242',
  //   menuParentId: '-1',
  //   breadcrumbParentId: '24',
  //   name: 'Edit Team',
  //   route: '/schedule/edit/:id',
  //   roles: ['admin', 'user'],
  // },
  // {
  //   id: '243',
  //   menuParentId: '-1',
  //   breadcrumbParentId: '24',
  //   name: 'Create Schedule',
  //   route: '/schedule/create',
  //   roles: ['admin', 'user'],
  // },
  {
    id: '3',
    name: 'Competitions',
    icon: 'star',
    route: '/competitions',
    roles: ['admin', 'user'],
  },
  {
    id: '31',
    menuParentId: '-1',
    breadcrumbParentId: '3',
    name: 'View Competition',
    route: '/competitions/view/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '32',
    menuParentId: '-1',
    breadcrumbParentId: '3',
    name: 'Create Competition',
    route: '/competitions/create',
    roles: ['admin', 'user'],
  },
  {
    id: '33',
    menuParentId: '-1',
    breadcrumbParentId: '3',
    name: 'Create Competition',
    route: '/competitions/edit/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '4',
    name: 'Contests',
    icon: 'star',
    roles: ['admin', 'user'],
  },
  {
    id: '41',
    menuParentId: '4',
    breadcrumbParentId: '4',
    name: 'User Contests',
    icon: 'star',
    route: '/contests',
    roles: ['admin', 'user'],
  },
  {
    id: '411',
    menuParentId: '-1',
    breadcrumbParentId: '41',
    name: 'User Contests Details',
    icon: 'star',
    route: '/contests/view/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '42',
    menuParentId: '4',
    breadcrumbParentId: '4',
    name: 'KKContests',
    icon: 'star',
    route: '/KKContests',
    roles: ['admin', 'user'],
  },
  {
    id: '421',
    menuParentId: '-1',
    breadcrumbParentId: '42',
    name: 'Create KKContests',
    route: '/KKContests/create',
    roles: ['admin', 'user'],
  },
  {
    id: '422',
    menuParentId: '-1',
    breadcrumbParentId: '42',
    name: 'Edit KKContests',
    route: '/KKContests/edit/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '423',
    menuParentId: '-1',
    breadcrumbParentId: '42',
    name: 'View KKContests',
    route: '/KKContests/view/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '43',
    menuParentId: '4',
    breadcrumbParentId: '4',
    name: 'Sponsored Contests',
    icon: 'star',
    route: '/sponsoredContests',
    roles: ['admin', 'user'],
  },
  {
    id: '431',
    menuParentId: '-1',
    breadcrumbParentId: '43',
    name: 'Create Sponsored Contests',
    route: '/sponsoredContests/create',
    roles: ['admin', 'user'],
  },
  {
    id: '432',
    menuParentId: '-1',
    breadcrumbParentId: '43',
    name: 'Edit Sponsored Contests',
    route: '/sponsoredContests/edit/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '433',
    menuParentId: '-1',
    breadcrumbParentId: '43',
    name: 'View Sponsored Contests',
    route: '/sponsoredContests/view/:id',
    roles: ['admin', 'user'],
  },
  {
    id: '5',
    name: 'Slider',
    icon: 'star',
    route: '/slider',
    roles: ['admin', 'user'],
  },
  {
    id: '51',
    menuParentId: '-1',
    breadcrumbParentId: '5',
    name: 'Create Slider',
    icon: 'star',
    route: '/slider/create',
    roles: ['admin', 'user'],
  },
  {
    id: '52',
    menuParentId: '-1',
    breadcrumbParentId: '5',
    name: 'Edit Slider',
    icon: 'star',
    route: '/slider/edit/:type',
    roles: ['admin', 'user'],
  },
  {
    id: '6',
    name: 'Banners',
    icon: 'star',
    route: '/banners',
    roles: ['admin', 'user'],
  },
  {
    id: '7',
    name: 'Home',
    route: '/home',
  },
  // {
  //   id: '8',
  //   name: 'Help',
  //   route: '/help',
  // },
  // {
  //   id: '9',
  //   name: 'About',
  //   route: '/about',
  // },
]
export default router
